<a href="https://colab.research.google.com/github/Aidan1223f/SERP_2022/blob/main/1stIteration.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.layers import Embedding, LSTM, Dense
from tensorflow.keras.models import Sequential
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.optimizers import Adam
import pickle
import numpy as np
import os

from google.colab import files
uploaded = files.upload()

Saving www-gutenberg-org-files-1342-1342-0-txt.txt to www-gutenberg-org-files-1342-1342-0-txt.txt


Preproccessing::

In [ ]:
 no thin file = open("www-gutenberg-org-files-1342-1342-0-txt.txt", "r", encoding = "utf8")


line = []
for i in file:
    line.append(i)


txtData = ""
for i in line:
  txtData = ' '. join(line) 

txtData = txtData.replace('\n', '').replace('\r', '').replace('\ufeff', '').replace('“','').replace('”','')  #new line, carriage return, unicode character --> replace by space

 
txtData = txtData.split()
txtData = ' '.join(txtData)
print(txtData[:300])

print(len(txtData))

The Project Gutenberg eBook of Pride and prejudice, by Jane Austen This eBook is for the use of anyone anywhere in the United States and most other parts of the world at no cost and with almost no restrictions whatsoever. You may copy it, give it away or re-use it under the terms of the Project Gute
104345


Tokenizer:

In [ ]:
token = Tokenizer(oov_token='<OOV>')
token.fit_on_texts([txtData])

# saving the tokenizer for predict function
pickle.dump(token, open('token.pkl', 'wb'))

seq_data = token.texts_to_sequences([txtData])[0]
print(seq_data[:30])
print(len(seq_data))

[2, 646, 501, 375, 3, 138, 5, 307, 27, 67, 116, 39, 375, 14, 22, 2, 427, 3, 871, 1347, 7, 2, 502, 872, 5, 86, 99, 873, 3, 2]
18732


In [ ]:
vocabSize =  len(token.word_index) + 1
print(vocabSize)

3043


Creates sequence of 3 words and predicted word 

In [ ]:
seq = []
for i in range(3, len(seq_data)): 
  wrd = seq_data[i-3 : i + 1]
  seq.append(wrd)

print("sequence length: " , len(seq))
seq = np.array(seq)
print(seq[:15])

sequence length:  18729
[[  2 646 501 375]
 [646 501 375   3]
 [501 375   3 138]
 [375   3 138   5]
 [  3 138   5 307]
 [138   5 307  27]
 [  5 307  27  67]
 [307  27  67 116]
 [ 27  67 116  39]
 [ 67 116  39 375]
 [116  39 375  14]
 [ 39 375  14  22]
 [375  14  22   2]
 [ 14  22   2 427]
 [ 22   2 427   3]]


Data represents the first 3 letters that the alg will be reading 
:  Predict represents predicted word

In [ ]:
data = []
predict = []

for i in seq:
    data.append(i[0:3])
    predict.append(i[3])
    
data = np.array(data)
predict = np.array(predict)

print(data)
print("/n")
print(predict)


[[  2 646 501]
 [646 501 375]
 [501 375   3]
 ...
 [ 45 178 234]
 [178 234  84]
 [234  84  79]]
/n
[ 375    3  138 ...   84   79 1089]
